import localFont from "next/font/local";
import "./globals.css";

import { getDocument } from "@/lib/doc";
import Header from "./components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  // const allDocuments = getDocument()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <main className="min-h-screen">

          {children}
        </main>
        <footer className="border-t border-t-gray-500 p-4">
          footer
        </footer>
      </body>
    </html >
  );
}
